### ISSUE TITLE
Docker run exited: Can't read /opt/connect/conf/mirth.properties: Permission denied

### ISSUE THREAD

**Issue by bartverhoevenaxxes** [nextgenhealthcare/connect-docker#4] opened 2020-02-19 11:49 UTC
OS: Ubuntu Server 16.04.6
Docker version: 19.03.6

The "docker run" command that is on the Nextgen Docker hub starts the container but exits immediately after starting with the following error: `sed: can't read /opt/connect/conf/mirth.properties: Permission denied`. This problem occurs since this week (19/02/2020) and occurs on multiple servers.

![Nextgen issue](https://user-images.githubusercontent.com/54616073/74831557-c0114f80-5315-11ea-8ff1-55ed73c8585f.jpg)

Version 3.8.0 starts without errors.

**Comment by cturczynskyj** [comment] 2020-02-19 19:13
I've tested this locally and cannot reproduce it. Here's my output:
```
$ docker run --name myconnect -d -p 8443:8443 nextgenhealthcare/connect:latest
Unable to find image 'nextgenhealthcare/connect:latest' locally
latest: Pulling from nextgenhealthcare/connect
dc65f448a2e2: Pull complete 
346ffb2b67d7: Pull complete 
dea4ecac934f: Pull complete 
f003f5c25f68: Pull complete 
ba2ac43bf199: Pull complete 
9599f5be1d38: Pull complete 
35c2257fb615: Pull complete 
d802968d8ffa: Pull complete 
46188f9a775c: Pull complete 
fce6720d12b5: Pull complete 
7ab76c471ab8: Pull complete 
aa519180c3bf: Pull complete 
062eaf310c4c: Pull complete 
9bf1a0aa5c1a: Pull complete 
804191eb3568: Pull complete 
Digest: sha256:fa4dbe35157489272ce5c613628b6a6ea418b3e9a320c079b01701c6bb4ac849
Status: Downloaded newer image for nextgenhealthcare/connect:latest
175f520cb0ab5f90acc5244fa3fb3ef5c1d11f93ed9b9dbc8a5443ec499de637
$ docker ps -a
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS                    PORTS                    NAMES
175f520cb0ab        nextgenhealthcare/connect:latest   "/entrypoint.sh ./mc…"   5 seconds ago       Up 4 seconds              0.0.0.0:8443->8443/tcp   myconnect
$ docker logs -f myconnect
INFO  2020-02-19 18:51:08,730 [Main Server Thread] com.mirth.connect.server.Mirth: Mirth Connect 3.8.1 (Built on September 12, 2019) server successfully started.
INFO  2020-02-19 18:51:08,737 [Main Server Thread] com.mirth.connect.server.Mirth: This product was developed by NextGen Healthcare (https://www.nextgen.com) and its contributors (c)2005-2020.
INFO  2020-02-19 18:51:08,739 [Main Server Thread] com.mirth.connect.server.Mirth: Running OpenJDK 64-Bit Server VM 11.0.6 on Linux (4.19.76-linuxkit, amd64), derby, with charset UTF-8.
INFO  2020-02-19 18:51:08,745 [Main Server Thread] com.mirth.connect.server.Mirth: Web server running at http://172.17.0.2:8080/ and https://172.17.0.2:8443/
$ docker container ls -a
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS                    PORTS                    NAMES
175f520cb0ab        nextgenhealthcare/connect:latest   "/entrypoint.sh ./mc…"   6 minutes ago       Up 6 minutes              0.0.0.0:8443->8443/tcp   myconnect
$ docker images
REPOSITORY                  TAG                 IMAGE ID            CREATED             SIZE
nextgenhealthcare/connect   latest              21b971b15a84        5 days ago          875MB
$ docker --version
Docker version 19.03.5, build 633a0ea
```
Do you see the same image ID?
`21b971b15a84`
and digest?
`sha256:fa4dbe35157489272ce5c613628b6a6ea418b3e9a320c079b01701c6bb4ac849`

Maybe try pulling the image again?

**Comment by cturczynskyj** [comment] 2020-04-14 18:02
Closing this issue, unable to reproduce

**Comment by cturczynskyj** [comment] 2020-04-14 18:02
Closing this issue, unable to reproduce.

**Closed by cturczynskyj** 2020-04-14 18:02 UTC
